name: Auto Release

on:
  push:
    tags:
    - '*'

jobs:

  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        skipIfReleaseExists: true
